mode: Mainline
branches:
  main:
    regex: main
  feature:
    regex: ^feature?[/-]
    increment: minor
    source-branches: ['main']
  bugfix:
    regex: ^bugfix?[/-]
    increment: patch
    source-branches: ['main']
