mode: Mainline
branches:
  main:
    tag: ""
    is-mainline: true
    increment: none
    is-source-branch-for: ['feature', 'fix']
  feature:
    increment: Minor
  fix:
    regex: bugfix(es)?[/-]
    increment: patch
    source-branches: ['develop', 'master']
ignore:
  sha: []
